config/routes.rb
Homepage::Application.routes.draw do

  get "posts/index"

  root :to => "Posts#index"
  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :name, :post_id, :created_at

  validates :content, presence: true
  validates :name, presence: true

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :created_at

  validates :content, presence: true
  validates :title, presence: true

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  	@post = Post.find(params[:post_id])
   	@comment = @post.comments.new(params[:comment])

  	respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment successfully posted.'}
        format.json { render json: @comment, status: :created }
      else
        format.html { redirect_to :back, notice: 'There was an error posting your comment.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
   end
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all(order: "created_at DESC")
  end

  def show
    @post = Post.find params[:id]
    @comments = @post.comments.order("created_at desc")
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new params[:post]

  	if @post.save
  		redirect_to root_path, :notice => 'A new post has been created.'
  	else
  		flash[:notice] = 'There was an error creating your post.'
  		render :action => 'new', :post => @post
  	end
  end

  def edit
  	@post = Post.find params[:id]
  end

  def update
  	@post = Post.find params[:id]
  	if @post.update_attributes params[:post]
  		redirect_to root_path, :notice => 'The post was succesfully updated.'
  	else
  		flash[:notice] = 'There was an error updating the post.'
  		render :action => 'edit', :post => @post
  	end
  end

  def destroy
  	Post.destroy params[:id]
  	redirect_to root_path, :notice => 'The post has been deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<div id="errors"></div>
<%= form_for Comment.new, :url => post_comments_path(@post) do |f| %>
	
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :content %>
	<%= f.text_area :content, rows: "5" %>

	<br>
	<%= f.submit %>

<% end %>

app/views/comments/_list.html.erb
<div id="comments" class="container clearfix">
<% for comment in @comments %>
	<div class="comment well">
		<h5><%= comment.name %></h5>
		<p><%=comment.content %></p>
    </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homepage</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="/">Homepage</a>
      <%= link_to 'New post', new_post_path, class: "btn btn-success pull-right" %>
    </div>
  </div>
</div>

<div class="container">
	<% flash.each do |name, message| %>
		<div class="alert alert-success" id="flash_<%= name %>">
			<%= message %>
		</div>
	<% end %>


	<div class="row">
			<div id="content" class="span8 offset1">
				<%= yield %>
			</div>
	
			<div id="sidebar" class="span3">
		</div>
	</div>
</div>

</body>
</html>

app/views/posts/_admin.html.erb
<div class="admin-btns pull-right">
	<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-info' %>
	<%= link_to 'Delete', @post, method: 'delete', class: 'btn btn-danger' %>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :content %>
	<%= f.text_area :content, rows: "10" %>

	<br>
	<%= f.submit %>

<% end %>

app/views/posts/_post_form.html.erb
<%= form_for @post do |f| %>
	
	<%= f.label :title %>
	<%= f.text_field :title %>

	<br>

	<%= f.label :content %>
	<%= f.text_area :content %>

	<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% for post in @posts %>

<div id="post_<%= post.id %>">
	<div class="well">
		<%= post.created_at %>
		<h3><%= link_to post.title, post %></h3>
		<%= post.content %>

		<hr>
		<div class="pull-right">
			<%= link_to 'Edit', edit_post_path(post), class: 'btn btn-info' %>
			<%= link_to 'Delete', post, method: 'delete', class: 'btn btn-danger' %>
		</div>
	</div>
</div>

<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @post.created_at %>
<h1><%= @post.title %></h1>
<%= @post.content %>

<div class="admin-buttons">
	<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-info' %>
	<%= link_to 'Delete', @post, method: 'delete', class: 'btn btn-danger' %>
</div>

<hr>

<%= render 'comments/form' %>

<%= render 'comments/list' %>